# Dependencies
markdown:         kramdown
highlighter:      pygments
kramdown:
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Jekyll Setup
gems: [jekyll-paginate, jekyll-gist]
paginate_path:    "page:num"
paginate:         5

# Setup
title:            Olin Gay
tagline:          'Putting it all together...'
description:      'Find me on Twitter <a href="http://twitter.com/olinbg" target="_blank">@olinbg</a> and <a href="http://linkedin.com/in/olinbg" target="_blank">LinkedIn</a>.'
url:              http://olinbg.github.io/
baseurl:          /

author:
  name:           'Olin Gay'
  url:            https://twitter.com/olinbg

# Custom vars
version:          0.0.2

github:
  profile:           https://github.com/olinbg